version: '3'
services:
  react-app:
  # need to add following line to resolve the issue mentioned here: https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
